"""Execution MCP tools."""

import logging
from typing import Any

from fastmcp.tools import tool

from bevault_mcp.states.client.deps import get_states_client

from bevault_mcp.states.models import (
    GetExecutionParams,
    ListExecutionsParams,
    StartExecutionParams,
    StartExecutionRequest,
)
from bevault_mcp.states.models.response.executions import (
    from_api_list_response,
    to_get_execution_response,
    to_start_execution_response,
)

logger = logging.getLogger(__name__)


client = get_states_client()


@tool()
def list_executions(
    stateMachineName: str,
    index: int = 0,
    pageSize: int = 10,
) -> dict:
    """
    List executions for a state machine in the beVault States module.

    Returns a paginated summary without input or output fields to keep
    the response compact. Use get_execution for full execution detail.

    Args:
        stateMachineName: Name of the state machine whose executions to list.
        index: Page index (0-based).
        pageSize: Number of results per page.

    Returns:
        A dict with paging info and a list of execution summaries.
    """
    try:
        params = ListExecutionsParams(
            stateMachineName=stateMachineName,
            index=index,
            pageSize=pageSize,
        )
        logger.info(
            "list_executions: stateMachineName=%s, index=%s, pageSize=%s",
            params.stateMachineName,
            params.index,
            params.pageSize,
        )
        api_response = client.executions.list_executions(
            params.stateMachineName,
            page_size=params.pageSize,
            index=params.index,
        )
        response = from_api_list_response(api_response)
        return response.model_dump(mode="json")
    except Exception:  # noqa: BLE001
        logger.exception("list_executions failed")
        raise


@tool()
def get_execution(stateMachineName: str, executionName: str) -> dict:
    """
    Get the full detail of a state machine execution.

    Returns execution status, input, output, dates, and error/cause when
    present. The nested state machine definition is omitted to save context;
    use get_state_machine for the full ASL definition.

    Args:
        stateMachineName: Name of the state machine.
        executionName: Name of the execution (case-sensitive).

    Returns:
        The execution detail as a dictionary.
    """
    try:
        params = GetExecutionParams(
            stateMachineName=stateMachineName,
            executionName=executionName,
        )
        logger.info(
            "get_execution: stateMachineName=%s, executionName=%s",
            params.stateMachineName,
            params.executionName,
        )
        execution = client.executions.get_execution(
            params.stateMachineName,
            params.executionName,
        )
        return to_get_execution_response(execution)
    except Exception:  # noqa: BLE001
        logger.exception("get_execution failed")
        raise


@tool()
def start_execution(
    stateMachineName: str,
    input: dict[str, Any] | None = None,
) -> dict:
    """
    Start a new execution of a state machine in the beVault States module.

    The execution name is auto-generated by the States API. The input
    is merged with the state machine's defaultInput.

    Args:
        stateMachineName: Name of the state machine to execute.
        input: Optional JSON input for the execution.

    Returns:
        The started execution as a dictionary (without the self URL).
    """
    try:
        params = StartExecutionParams(
            stateMachineName=stateMachineName,
            input=input,
        )
        logger.info(
            "start_execution: stateMachineName=%s",
            params.stateMachineName,
        )
        request = StartExecutionRequest(input=params.input or {})
        execution = client.executions.start_execution(
            params.stateMachineName,
            request,
        )
        return to_start_execution_response(execution)
    except Exception:  # noqa: BLE001
        logger.exception("start_execution failed")
        raise
