"""beVault MCP models package."""
# API models (contract with beVault API)
from .api import (
    BaseModelEntity,
    BusinessKey,
    DataPackage,
    Hub,
    InformationMart,
    InformationMartScript,
    Link,
    ModelEntity,
    Project,
    ReferenceTable,
    Satellite,
    Snapshot,
    SourceSystem,
    StagingTable,
    EmbeddedEntities,
    EmbeddedProjects,
    EmbeddedSourceSystems,
    InformationMarts,
    InformationMartsResponse,
    ProjectsResponse,
    SearchResponse,
    Snapshots,
    SnapshotsResponse,
    SourceSystemsResponse,
)

# Request models (for tool inputs)
from .requests import (
    BusinessKeyRequest,
    CreateDataPackageRequest,
    CreateHubRequest,
    CreateInformationMartRequest,
    CreateInformationMartScriptRequest,
    CreateLinkRequest,
    UpdateInformationMartScriptRequest,
    UpdateInformationMartScriptColumnRequest,
    UpdateSourceColumnRequest,
    CreateSourceSystemRequest,
    CreateStagingTableRequest,
    DependentChildColumn,
    StagingTableColumn,
    HubReference,
    LinkType,
    SearchParams,
)

# Response models (optimized for MCP tools)
from .response import (
    OptimizedDataPackage,
    OptimizedEntity,
    OptimizedHub,
    OptimizedInformationMart,
    OptimizedInformationMartScript,
    OptimizedInformationMartsResponse,
    OptimizedLink,
    OptimizedReferenceTable,
    OptimizedSatellite,
    OptimizedSearchResponse,
    OptimizedSourceSystem,
    OptimizedSourceSystemsResponse,
    PagingInfo,
    StagingTableInfo,
)

__all__ = [
    # API Entities
    "BaseModelEntity",
    "BusinessKey",
    "DataPackage",
    "Hub",
    "InformationMart",
    "InformationMartScript",
    "Link",
    "ModelEntity",
    "Project",
    "ReferenceTable",
    "Satellite",
    "Snapshot",
    "SourceSystem",
    "StagingTable",
    # API Responses
    "EmbeddedEntities",
    "EmbeddedProjects",
    "EmbeddedSourceSystems",
    "InformationMarts",
    "InformationMartsResponse",
    "ProjectsResponse",
    "SearchResponse",
    "Snapshots",
    "SnapshotsResponse",
    "SourceSystemsResponse",
    # Requests
    "BusinessKeyRequest",
    "CreateDataPackageRequest",
    "CreateHubRequest",
    "CreateInformationMartRequest",
    "CreateInformationMartScriptRequest",
    "CreateLinkRequest",
    "CreateSourceSystemRequest",
    "CreateStagingTableRequest",
    "DependentChildColumn",
    "StagingTableColumn",
    "HubReference",
    "LinkType",
    "SearchParams",
    "UpdateInformationMartScriptRequest",
    "UpdateInformationMartScriptColumnRequest",
    "UpdateSourceColumnRequest",
    # Optimized Responses
    "OptimizedDataPackage",
    "OptimizedEntity",
    "OptimizedHub",
    "OptimizedInformationMart",
    "OptimizedInformationMartScript",
    "OptimizedInformationMartsResponse",
    "OptimizedLink",
    "OptimizedReferenceTable",
    "OptimizedSatellite",
    "OptimizedSearchResponse",
    "OptimizedSourceSystem",
    "OptimizedSourceSystemsResponse",
    "PagingInfo",
    "StagingTableInfo",
]
